### ISSUE TITLE
React GUI: Display current services in sidebar

### ISSUE THREAD

**Issue by nlicalzi** [dendro-naap/dendro-cli#62]
Thoughts @awcrotwell ? Afraid we're going to have breaking queries if we just have pages for everything by default

**Comment by AndiLavera** [comment]
Yes that's the plan. I can get that done tomorrow. 

https://github.com/dendro-naap/dendro-cli/blob/a526b3493e1c31dc462ea2a6d3e1f418ad30b063/src/pages/_app.tsx#L9

Right now the services are hard coded. Tomorrow i can turn this into an api call. I figured going based off of timestream database names would be best since those are ALL services monitored by users. It will fetch the services & pass them into sidebar as seen on line 28 :smile:

**Comment by AndiLavera** [comment]
Completed with #67
